services:
  db:
    image: ${DB_VERSION:-mariadb:11.8}
    container_name: pkp_db_ojs
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeMePlease}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pkp}
      MYSQL_USER: ${MYSQL_USER:-pkp}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeMePlease}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PKP_TOOL: ${PKP_TOOL:-ojs}
        PKP_VERSION: ${PKP_VERSION:-3_4_0-8}
        WEB_SERVER: ${WEB_SERVER:-php:8.2-apache}
        BUILD_PKP_APP_OS: ${BUILD_PKP_APP_OS:-alpine:3.22}
    image: local/ojs:${PKP_VERSION:-3_4_0-8}
    container_name: pkp_app_ojs
    env_file:
      - .env
    environment:
      SERVERNAME: ${SERVERNAME:-localhost}
      PKP_DB_HOST: ${DB_HOST:-db}
      PKP_DB_NAME: ${DB_NAME:-pkp}
      PKP_DB_USER: ${DB_USER:-pkp}
      PKP_DB_PASSWORD: ${DB_PASS:-changeMePlease}
      PKP_CLI_INSTALL: ${PKP_CLI_INSTALL:-0}
    user: "0:0"
    command: >
      bash -lc "mkdir -p /var/www/files/temp /var/www/files/usageStats/usageEventLogs && chown -R www-data:www-data /var/www/files && chmod -R ug+rwX /var/www/files && exec /usr/local/bin/pkp-start"
    ports:
      - "${HTTP_PORT:-8080}:80"
      - "${HTTPS_PORT:-8443}:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/private:/var/www/files
      - ./volumes/public:/var/www/html/public
      - ./volumes/config/pkp.config.inc.php:/var/www/html/config.inc.php
      - ./volumes/config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      - db
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pkp_db_ui_ojs
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    ports:
      - "${PMA_PORT:-8081}:80"
    depends_on:
      - db
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: pkp_mailpit_ojs
    ports:
      - "${MAILPIT_SMTP_PORT:-1125}:1125"
      - "${MAILPIT_WEB_PORT:-8026}:8026"
    restart: unless-stopped
